### ISSUE TITLE
Ch. 6 Q: Federated queries across SPARQL endpoints

### ISSUE THREAD

**Issue by mdeagen** [Semantic-Web-Working-Ontologist/KGCBookClub#43]
Query federation using the `SERVICE` keyword is a nice demonstration of dataset interoperability. 

Practically speaking, what are some of the biggest limitations to querying across distributed endpoints (in terms of access, as well as the amount of data that can be passed between endpoints in the execution of a query)? 

Is there a good up-to-date list of public SPARQL endpoints? (The [list on W3C wiki](https://www.w3.org/wiki/SparqlEndpoints) returns a lot of 404's and 503's, and the [SPARQLES system](https://sparqles.ai.wu.ac.at/) returns a 502...)

**Comment by dallemang** [comment]
A list of public SPARQL endpoints is like a list of web pages; they are pretty easy to set up, and there are a bunch of them out there.  data.world has recently added a feature whereby any of their public data sets includes a SPARQL endpoint, so there are millions of them now.  

The biggest issue I have found with using SERVICE endpoint calls is arranging them so that the queries are performant; because of the execution order specification in SPARQL, it is easy to accidentally have the remote endpoint run a query that is open-ended, and then filter on your end; this is just the opposite of what you want.  You want to have the remote server run a query that is as specific as possible, and run as little data across the line as you can.    Sometimes that is difficult to orchestrate in SPARQL. 

I haven't experienced a lot of access issues, since I have either used open endpoints, or endpoints within an enterprise that are protected by the enterprise firewall (and hence, nothing between me and them).  That is obviously a potential issue, but I haven't run into it a lot.
