### ISSUE TITLE
Ch 11 SKOS and Ch 10 Schema.org

### ISSUE THREAD

**Issue by ghost** [Semantic-Web-Working-Ontologist/KGCBookClub#56]
There seems to be a common mathematical principle between the two ontologies in deference to RDF to OWL.  They (I assume) use a less exacting underlying mathematical logic.  Could you cite some readings that would help get a solid understanding of the underlying math logic. I think this would help me feel more confident in understanding how the differing semantic approaches work.  I recognize this is out of the scope of the bookclub.  Thanks Bob Lucas

**Comment by dallemang** [comment]
You are correct; there are actually three mathematical systems  going on here.  

RDF - basic statements (FOPC).  Blank nodes are officially existential quantifiers.  You can draw simple conclusions based on RDF, but so simple, they barely merit mention.  I'm not sure where that's written up.   A lot of the RDF inferencing (with RDF+Rules, in a non-standard form) is embodied in a system called cwm https://www.w3.org/2000/10/swap/doc/cwm

RDFS - basic syllogisms, which we talked about in the past chapter.  You probably noticed that there is a base class called rdfs:Class in the metamodel.  My recollection is that the definition of an rdfs:Class is vulnerable to Russell's Paradox, and is hence actually incoherent. 

OWL - Description Logic.  You have probably noticed that owl:Class is a distinct subclass of rdfs:Class, and that's probably what made you suspect that there are some different mathematical logics going on there.  owl:Class is not vulnerable to Russell's Paradox, since membership in a class (intentionally) is defined by restrictions in Description Logic, which are not expressive enough to talk about Russell's Paradox.  Also, DL is not vulnerable to Gödel's incompleteness theorem.  And if you remember your details of that, you're realizing that this means that OWL can't talk fully about the integers.  This is why datatypes live outside the scope of the OWL definition (they are relegated to external sets that OWL can reference but not reason over).  

As for a resource for all this stuff; I don't even remember where I learned it.  I took a few courses in mathematical logic and decideability theory in grad school (long before RDFS or OWL existed), and talked with many of the folks on the OWL committee back in the day about their concerns over the logic; I probably learned all this stuff over a beer or seven.  I believe that the Semantic Web Primer (https://mitpress.mit.edu/books/semantic-web-primer-third-edition), which I admit I have not read, despite being close friends with one of the authors, covers a lot of this material.   Judging from the table of contents and the authors' interests, I think this is probably your best resource for learning about this stuff.
